# Generated by Django 5.0 on 2024-11-05 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_description_1_product_description_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referans Kodu')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Birim Fiyat')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Ürün Adeti')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Toplam Fiyat')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('received', 'Sipariş Verildi'), ('preparing', 'Sipariş Hazırlanıyor'), ('in_shipping', 'Sipariş Kargoda'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Sipariş Durumu')),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='order_images/', verbose_name='Ürün Fotoğrafı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sipariş Veren Kişi')),
            ],
        ),
    ]
