# Generated by Django 5.0 on 2024-11-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün'),
        ),
    ]
