# Generated by Django 5.1.2 on 2024-11-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyadı')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('mahalle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahelle')),
                ('address_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres Başlığı')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Adresi Oluşturan Kişi')),
            ],
        ),
    ]
