# Generated by Django 5.1.2 on 2024-11-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_temporaryemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryEmail',
        ),
    ]
